to_string fix C4702
I spotted this line looks like another instance that'll cause a C4702 unreachable code.

D:\dev\OpenVIII_CPP_WIP\cmake-build-debug-visual-studio\_deps\ctre_fetch-src\include\ctre\return_type.hpp(131) : error C2220: the following warning is treated as an error
D:\dev\OpenVIII_CPP_WIP\cmake-build-debug-visual-studio\_deps\ctre_fetch-src\include\ctre\return_type.hpp(131) : warning C4702: unreachable code