change size_t to auto std::distance returns long int
```shell
_deps/ctre_fetch-src/include/ctre/first.hpp:357:31: error: conversion to â€˜size_tâ€™ {aka â€˜long unsigned intâ€™} from â€˜std::iterator_traits<ctre::point_set<1>::point*>::difference_typeâ€™ {aka â€˜long intâ€™} may change the sign of the result [-Werror=sign-conversion]
```
by changing it to auto the code should still work and won't need to static cast or implicitly cast to size_t.